### ISSUE TITLE
Fix wiki structure

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/nlpsandbox.io#28]
The CI/CD workflow failed when merging the last PR, which I kind of expected giving the scale of the refactoring.

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.6.12/x64/bin/challengeutils", line 8, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/challengeutils/__main__.py", line 804, in main
    args.func(syn, args)
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/challengeutils/__main__.py", line 335, in command_push_wiki
    wiki_headers = wiki.push_wiki(syn, args.projectid, workdir=args.workdir)
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/challengeutils/wiki.py", line 188, in push_wiki
    wiki_config = validate_config(workdir)
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/challengeutils/wiki.py", line 151, in validate_config
    raise ValueError(f"{markdown_path} does not exist")
ValueError: 608037-DateAnnotation.md does not exist
Error: Process completed with exit code 1.
```

**Comment by tschaffter** [comment]
The error is still there, but I can successfully run the push command locally.

**Comment by tschaffter** [comment]
It looks like it's an issue with the file names. This is not the first time GitHub is not able to distinguish between upper and lowercases.

Here is what I have locally after running `git pull`

```
$ ls -al
total 68
drwxr-xr-x 1 tschaffter tschaffter 4096 Feb  2 19:54 .
drwxr-xr-x 1 tschaffter tschaffter 4096 Feb  2 19:30 ..
-rw-r--r-- 1 tschaffter tschaffter 4022 Jan 29 10:13 604825-homepage.md
-rw-r--r-- 1 tschaffter tschaffter  515 Jan 29 10:13 604826-Data.md
-rw-r--r-- 1 tschaffter tschaffter  542 Feb  2 19:53 604827-HowtoParticipate.md
-rw-r--r-- 1 tschaffter tschaffter   58 Jan 29 10:13 604828-Leaderboards.md
-rw-r--r-- 1 tschaffter tschaffter 2383 Feb  2 19:28 604831-Rules.md
-rw-r--r-- 1 tschaffter tschaffter 4082 Jan 29 10:13 604834-SubmissionTutorial.md
-rw-r--r-- 1 tschaffter tschaffter  270 Feb  2 19:28 604836-DevelopersTeams.md
-rw-r--r-- 1 tschaffter tschaffter 5431 Jan 29 10:13 604837-ParticipationOverview.md
-rw-r--r-- 1 tschaffter tschaffter 1810 Feb  2 19:28 604838-SubmissionDashboards.md
-rw-r--r-- 1 tschaffter tschaffter  323 Feb  2 19:28 607367-Admin.md
-rw-r--r-- 1 tschaffter tschaffter  486 Feb  2 19:28 607785-DateAnnotationAdmin.md
-rw-r--r-- 1 tschaffter tschaffter  486 Feb  2 19:28 607786-PersonNameAnnotationAdmin.md
-rw-r--r-- 1 tschaffter tschaffter  486 Feb  2 19:28 607787-PhysicalAddressAnnotationAdmin.md
-rw-r--r-- 1 tschaffter tschaffter 9738 Jan 29 10:13 607935-Tasks.md
-rw-r--r-- 1 tschaffter tschaffter    0 Feb  2 16:44 608036-PersonNameAnnotation.md
-rw-r--r-- 1 tschaffter tschaffter    0 Feb  2 16:44 608037-DateAnnotation.md
-rw-r--r-- 1 tschaffter tschaffter    0 Feb  2 16:45 608038-PhysicalAddressAnnotation.md
-rw-r--r-- 1 tschaffter tschaffter    0 Feb  2 19:28 608039-DateAnnotationLeaderboard.md
-rw-r--r-- 1 tschaffter tschaffter    0 Feb  2 19:28 608040-PersonNameAnnotationLeaderboard.md
-rw-r--r-- 1 tschaffter tschaffter    0 Feb  2 19:28 608041-PhysicalAddressAnnotationLeaderboard.md
-rw-r--r-- 1 tschaffter tschaffter 1264 Feb  2 14:58 608145-SubmissionLogs.md
-rw-r--r-- 1 tschaffter tschaffter    0 Feb  2 19:28 608219-Datasets.md
-rw-r--r-- 1 tschaffter tschaffter    0 Feb  2 19:28 608220-DateAnnotationDashboard.md
-rw-r--r-- 1 tschaffter tschaffter    0 Feb  2 19:28 608221-PersonNameAnnotationDashboard.md
-rw-r--r-- 1 tschaffter tschaffter    0 Feb  2 19:28 608222-PhysicalAddressAnnotationDashboard.md
-rw-r--r-- 1 tschaffter tschaffter    0 Feb  2 19:28 608223-2014i2b2NLPDeidChallengeDataset.md
-rw-r--r-- 1 tschaffter tschaffter 4278 Feb  2 19:54 wiki_config.json
```

Here are the filenames visible on GH:

![image](https://user-images.githubusercontent.com/3056480/106696314-48bde580-6591-11eb-9341-7933db0fcfa2.png)

**Comment by tschaffter** [comment]
The solution was to rename the file, commit, rename and commit again.
